import { notFound } from "next/navigation";
import Link from "next/link";
import { latestOperation } from "@/lib/deployment/service";
import { NextStep } from "@/components/projects/next-step";
import { DetailSection } from "@/components/evaluations/detail-section";
import { ReportTestResults } from "@/components/reports/report-test-results";
import { FailureRecurrences } from "@/components/reports/failure-recurrences";
import { buildFailureRecurrences } from "@/lib/evaluation/recurrence";
import { analyzeRunWithAi, buildDeterministicRunFindings, buildRunAnalysisPayload, type RunAnalysisStatus } from "@/lib/ai/run-analysis";
import {
  completeRunAnalysis,
  isEvaluationAiConfigured,
} from "@/lib/ai/client";
import { getEvaluationDatasetByModelId } from "@/lib/data/evaluation-engine";
import {
  getEvaluationById,
  getEvaluationResultsByEvaluationIds,
} from "@/lib/data/evaluations";
import { getEffectiveModelVersionConfiguration } from "@/lib/data/model-configurations";
import { getModelById } from "@/lib/data/models";
import {
  getVersionById,
  getVersionChangesByVersionIds,
} from "@/lib/data/versions";
import { buildRunReportData, hasReportExecutionError, type PerTestReportRow, type TelemetryCoverage } from "@/lib/evaluation/report-data";
import { prioritizeReportTests, shouldGenerateRunAnalysis } from "@/lib/evaluation/report-priority";
import { recallRunReportMemory } from "@/lib/hindsight/report-recall";
import { buildEvidenceGroundedRecommendations, selectReportRecommendations } from "@/lib/evaluation/recommendations";
import { isHindsightConfigured } from "@/lib/hindsight/client";
import { recallEvaluationDetailMemory } from "@/lib/hindsight/recall";
import {
  backfillReportMemories,
  buildStoredReportMemories,
} from "@/lib/hindsight/report-memory";
import type { EvaluationDetailRecallGroups } from "@/lib/hindsight/recall";
import type { HindsightRecallMemory } from "@/lib/hindsight/types";

export const dynamic = "force-dynamic";
export const maxDuration = 240;

type EvaluationDetailPageProps = {
  params: Promise<{ id: string }>;
  searchParams?: Promise<{ ai?: string; memory?: string }>;
};

const dateFormatter = new Intl.DateTimeFormat("en", {
  month: "short",
  day: "numeric",
  year: "numeric",
});

function formatDate(value: string) {
  return dateFormatter.format(new Date(value));
}

function formatPercent(value: number | null) {
  return value === null ? "Not recorded" : `${Math.round(value * 100)}%`;
}

function formatNumber(value: number | null | undefined, suffix = "") {
  return typeof value === "number" && Number.isFinite(value)
    ? `${value.toLocaleString()}${suffix}`
    : "Not recorded";
}

function formatCompactNumber(value: number | null | undefined) {
  if (typeof value !== "number" || !Number.isFinite(value)) return "Not recorded";
  if (Math.abs(value) >= 1000) return `${(value / 1000).toFixed(1)}K`;
  return value.toLocaleString();
}

function formatTelemetry(value: number | null, coverage: TelemetryCoverage, formatter = formatCompactNumber) {
  const formatted = formatter(value);
  return value !== null && coverage.recorded < coverage.total ? `${formatted} (partial: ${coverage.recorded}/${coverage.total} tests)` : formatted;
}

function formatCurrency(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value)
    ? `$${value.toFixed(6)}`
    : "Not recorded";
}

function formatDecimal(value: number | null | undefined, digits = 2) {
  return typeof value === "number" && Number.isFinite(value)
    ? value.toFixed(digits)
    : "Not recorded";
}

function formatLatencySeconds(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value)
    ? `${(value / 1000).toFixed(2)}s`
    : "Not recorded";
}

function getRunMode(value: unknown) {
  return (
    typeof value === "object" &&
    value &&
    !Array.isArray(value) &&
    "mode" in value &&
    typeof value.mode === "string"
  )
    ? value.mode
    : "legacy/manual";
}

function PageMessage({
  title,
  description,
}: Readonly<{ title: string; description: string }>) {
  return (
    <section className="rounded-md border border-slate-200 bg-white p-6">
      <h2 className="text-sm font-semibold text-slate-950">{title}</h2>
      <p className="mt-2 text-sm leading-6 text-slate-600">{description}</p>
    </section>
  );
}

function AnalysisSection({
  evaluationId,
  configured,
  result,
  generated,
  autoGenerated,
  disabled,
  memoryEnabled,
  fallback,
}: Readonly<{
  evaluationId: string;
  configured: boolean;
  result: RunAnalysisStatus | null;
  generated: boolean;
  autoGenerated: boolean;
  disabled: boolean;
  memoryEnabled: boolean;
  fallback: string;
}>) {
  const unavailableMessage = !configured
    ? "AI analysis is not configured."
    : result && !result.ok
      ? result.message
      : "AI analysis temporarily unavailable.";

  return (
    <DetailSection
      label="MODELLEDGER ANALYSIS"
      title="ModelLedger analysis"
      description="Run-wide interpretation of stored facts, prioritized test evidence, version changes, and related history."
    >
      {!generated ? (
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm leading-6 text-slate-600">
            {configured
              ? disabled
                ? "AI analysis generation is turned off for this view."
                : autoGenerated
                  ? "AI analysis is generated for high-priority issues."
                  : fallback
              : "AI analysis is not configured."}
          </p>
          {configured ? (
            <Link
              href={`/reports/${evaluationId}?memory=${memoryEnabled ? "on" : "off"}&ai=on`}
              className="inline-flex h-9 items-center justify-center rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-950 transition-colors hover:bg-slate-50 active:translate-y-px"
            >
              Generate Analysis
            </Link>
          ) : null}
        </div>
      ) : !configured || !result || !result.ok ? (
        <p className="text-sm leading-6 text-slate-600">{unavailableMessage}</p>
      ) : (
        <div className="grid gap-3">
          <p className="text-sm leading-6 text-slate-700">
            {result.analysis.executiveSummary}
          </p>
          <p className="text-sm font-semibold text-slate-950">
            Confidence: {result.analysis.confidence}
          </p>
        </div>
      )}
    </DetailSection>
  );
}

function MemoryEvidenceSection({
  evaluationId,
  enabled,
  configured,
  recallGroups,
  memories,
  unavailableOverride = false,
}: Readonly<{
  evaluationId: string;
  enabled: boolean;
  configured: boolean;
  recallGroups: EvaluationDetailRecallGroups | null;
  memories: readonly HindsightRecallMemory[];
  unavailableOverride?: boolean;
}>) {
  const unavailable = unavailableOverride || (recallGroups
    ? [
        recallGroups.similarFailures,
        recallGroups.previousResolutions,
        recallGroups.historicalRegressions,
        recallGroups.relevantVersionChanges,
      ].some((result) => !result.ok)
    : false);
  const visibleMemories = memories.slice(0, 3);

  return (
    <DetailSection
      label="HISTORICAL EVIDENCE"
      title="Historical evidence"
      description="Related stored history and recalled Hindsight memory are evidence, not proof of causation."
    >
      <div className="mb-4 flex flex-wrap items-center gap-2">
        <Link
          href={`/reports/${evaluationId}?memory=off`}
          className={`rounded-sm border px-3 py-1.5 text-sm font-semibold ${
            !enabled
              ? "border-slate-950 bg-slate-950 text-white"
              : "border-slate-200 text-slate-700"
          }`}
        >
          Without Memory
        </Link>
        <Link
          href={`/reports/${evaluationId}?memory=on`}
          className={`rounded-sm border px-3 py-1.5 text-sm font-semibold ${
            enabled
              ? "border-slate-950 bg-slate-950 text-white"
              : "border-slate-200 text-slate-700"
          }`}
        >
          With Memory
        </Link>
      </div>
      {enabled && unavailable && visibleMemories.length > 0 && <p className="mb-3 text-sm text-amber-800">Historical recall is partially unavailable. The evidence below includes the available stored or recalled records.</p>}

      {!enabled ? (
        <p className="text-sm leading-6 text-slate-600">
          Without Memory mode shows only current stored facts and deterministic analysis.
        </p>
      ) : (!configured || unavailable) && visibleMemories.length === 0 ? (
        <p className="text-sm leading-6 text-slate-600">
          Historical memory is temporarily unavailable.
        </p>
      ) : visibleMemories.length === 0 ? (
        <p className="text-sm leading-6 text-slate-600">
          No related historical issue found. This may be a new failure pattern.
        </p>
      ) : (
        <div className="grid gap-3">
          {visibleMemories.map((memory) => (
            <article key={memory.id} className="rounded-md border border-slate-200 p-4">
              <div className="flex flex-wrap items-center gap-2 text-xs font-medium uppercase tracking-[0.08em] text-slate-500">
                <span>{memory.id.startsWith("stored:") ? "Stored history" : "Recalled memory"} · {memory.eventType?.replaceAll("_", " ") ?? "Memory"}</span>
                <span>{memory.version ?? memory.modelVersionId ?? "Version not recorded"}</span>
                <span>{memory.timestamp ? formatDate(memory.timestamp) : "Date not recorded"}</span>
              </div>
              <p className="mt-2 text-sm leading-6 text-slate-700">
                {memory.content}
              </p>
            </article>
          ))}
        </div>
      )}
    </DetailSection>
  );
}

function TestBreakdownTable({
  tests,
  fallbackLabel,
}: Readonly<{ tests: readonly PerTestReportRow[]; fallbackLabel: string }>) {
  if (tests.length === 0) {
    return <p className="text-sm leading-6 text-stone-600">{fallbackLabel}</p>;
  }

  return (
    <div className="overflow-x-auto">
      <table className="min-w-[760px] text-left text-sm">
        <thead className="border-b border-stone-200 text-xs uppercase tracking-[0.08em] text-stone-500">
          <tr>
            <th className="px-3 py-2">Test</th>
            <th className="px-3 py-2">Previous</th>
            <th className="px-3 py-2">Current</th>
            <th className="px-3 py-2">Score Change</th>
            <th className="px-3 py-2">Category</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-stone-200">
          {tests.map((test) => (
            <tr key={test.id}>
              <td className="px-3 py-3 font-semibold text-stone-950">{test.testName}</td>
              <td className="px-3 py-3 text-stone-700">
                {test.baselineResult ?? "No baseline"}
              </td>
              <td className="px-3 py-3 text-stone-700">{test.result}{hasReportExecutionError(test) ? " (execution/evaluator error)" : ""}</td>
              <td className="px-3 py-3 text-stone-700">
                {test.scoreDelta === null ? "No baseline" : formatDecimal(test.scoreDelta)}
              </td>
              <td className="px-3 py-3 text-stone-700">{test.category}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

async function getEvaluationDetailState(evaluationId: string) {
  try {
    const evaluation = await getEvaluationById(evaluationId);
    if (!evaluation) return { status: "not-found" as const };

    const [model, version, results, versionChanges, configuration] = await Promise.all([
      getModelById(evaluation.model_id),
      getVersionById(evaluation.model_version_id),
      getEvaluationResultsByEvaluationIds([evaluation.id]),
      getVersionChangesByVersionIds([evaluation.model_version_id]),
      getOptionalModelVersionConfiguration(evaluation.model_version_id),
    ]);

    if (!model || !version) return { status: "not-found" as const };

    return {
      status: "ready" as const,
      evaluation,
      model,
      version,
      results,
      versionChanges,
      configuration,
    };
  } catch (error) {
    return {
      status: "error" as const,
      description:
        error instanceof Error
          ? error.message
          : "The evaluation detail page could not load Supabase-backed data.",
    };
  }
}

async function getOptionalModelVersionConfiguration(modelVersionId: string) {
  try {
    return await getEffectiveModelVersionConfiguration(modelVersionId);
  } catch {
    return null;
  }
}

export default async function EvaluationDetailPage({
  params,
  searchParams,
}: EvaluationDetailPageProps) {
  const { id } = await params;
  const resolvedSearchParams = await searchParams;
  const memoryEnabled = resolvedSearchParams?.memory !== "off";
  const aiRequested = resolvedSearchParams?.ai === "on";
  const aiDisabled = resolvedSearchParams?.ai === "off";
  const state = await getEvaluationDetailState(id);

  if (state.status === "not-found") notFound();

  if (state.status === "error") {
    return (
      <PageMessage
        title="Evaluation unavailable"
        description={state.description}
      />
    );
  }

  if (state.results.length === 0) {
    return (
      <PageMessage
        title="No evaluation results found"
        description="This evaluation run exists, but no individual test results are stored yet."
      />
    );
  }

  const relevantVersionChange =
    state.versionChanges.filter((change) => Date.parse(change.created_at) <= Date.parse(state.evaluation.evaluated_at)).find((change) => change.change_type === "SYSTEM_PROMPT") ??
    state.versionChanges.find((change) => Date.parse(change.created_at) <= Date.parse(state.evaluation.evaluated_at));
  const evaluationDataset = await getEvaluationDatasetByModelId(state.model.id);
  const recurrenceEvidence = await Promise.all([
    getEvaluationResultsByEvaluationIds([...new Set(evaluationDataset.facts.map((fact) => fact.evaluationId))]),
    getVersionChangesByVersionIds(evaluationDataset.versions.map((version) => version.id)),
  ]).catch(() => null);
  const recurrences = recurrenceEvidence ? buildFailureRecurrences({ dataset: evaluationDataset, evaluationId: id, results: recurrenceEvidence[0], versionChanges: recurrenceEvidence[1] }) : [];
  const report = buildRunReportData({
    evaluation: state.evaluation,
    results: state.results,
    dataset: evaluationDataset,
    configuration: state.configuration,
  });
  const hindsightConfigured = isHindsightConfigured();
  const shouldRecallMemory =
    memoryEnabled &&
    (report.failed > 0 || report.regressions > 0 || report.improvements > 0 || report.errors > 0);
  const storedReportMemories = shouldRecallMemory
    ? buildStoredReportMemories({
        dataset: evaluationDataset,
        report,
        modelName: state.model.name,
      })
    : [];
  if (shouldRecallMemory && hindsightConfigured) {
    await backfillReportMemories({
      modelId: state.model.id,
      modelName: state.model.name,
      dataset: evaluationDataset,
      report,
    });
  }
  const recalled = shouldRecallMemory && hindsightConfigured
    ? await recallRunReportMemory(state.model.id, report, recallEvaluationDetailMemory)
    : { groups: null, all: [], unavailable: false };
  const memoryRecall = recalled.groups;
  const reportMemories = [...new Map([...recalled.all, ...storedReportMemories].map((memory) => [memory.id, memory])).values()];
  const aiConfigured = isEvaluationAiConfigured();
  const shouldAutoGenerateAi = shouldGenerateRunAnalysis(report);
  const shouldGenerateAi =
    aiConfigured && !aiDisabled && (shouldAutoGenerateAi || aiRequested);
  const aiAnalysis = shouldGenerateAi
    ? await analyzeRunWithAi(
        {
          model: state.model,
          version: state.version,
          report,
          versionChanges: state.versionChanges,
          memories: reportMemories,
        },
        completeRunAnalysis,
      )
    : null;
  const aiResult = aiAnalysis && aiAnalysis.ok ? aiAnalysis.analysis : null;
  const deterministicActions = buildEvidenceGroundedRecommendations({ report, memories: reportMemories, versionChanges: state.versionChanges });
  const evidenceInventory = buildRunAnalysisPayload({ model: state.model, version: state.version, report, versionChanges: state.versionChanges, memories: reportMemories }).evidence;
  const recommendations = selectReportRecommendations(report, deterministicActions, aiResult);
  const regressionTests = report.tests.filter((test) => test.classification === "REGRESSION");
  const improvementTests = report.tests.filter((test) => test.classification === "RESOLVED");
  const failedTests = prioritizeReportTests(report.tests.filter((test) => test.result === "FAIL" && !hasReportExecutionError(test)));
  const executionErrors = report.tests.filter(hasReportExecutionError);
  const findings = aiResult?.findings ?? buildDeterministicRunFindings(report);
  const changeRows = aiResult?.findings.map((finding) => ({ change: `${finding.kind}: ${finding.title}`, impact: finding.description, evidence: finding.evidenceRefs.join(", ") })).slice(0, 4) ?? [];
  const inputTokens = report.inputTokens;
  const outputTokens = report.outputTokens;
  const operation = await latestOperation(state.model.id);

  return (
    <div className="space-y-7">
      {operation && <NextStep key={`${operation.id}:${operation.updated_at}`} initial={operation} report />}
      <Link href={`/projects/${state.model.id}`} className="text-sm text-stone-600 underline">← Back to {state.model.name}</Link>
      <header className="flex flex-col gap-4 border-b border-stone-200 pb-5 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-500">
            Run Report
          </p>
          <h1 className="mt-2 text-2xl font-semibold tracking-normal text-stone-950">
            {state.model.name}
          </h1>
          <p className="mt-2 text-sm leading-6 text-stone-600">
            Version {state.version.version} · Run {state.evaluation.id} · Evaluated{" "}
            {formatDate(state.evaluation.evaluated_at)}
          </p>
        </div>
        <nav className="flex flex-wrap gap-2">
          <Link
            href={`/compare?project=${state.model.id}&to=${state.version.id}`}
            className="inline-flex h-9 items-center justify-center rounded-md border border-stone-200 bg-white px-3 text-sm font-semibold text-stone-700"
          >
            Compare Version
          </Link>
          <Link
            href={`/run-evaluation?project=${state.model.id}&version=${state.version.id}`}
            className="inline-flex h-9 items-center justify-center rounded-md bg-stone-950 px-3 text-sm font-semibold text-white"
          >
            Run Again
          </Link>
        </nav>
      </header>

      <section className="rounded-md border border-stone-200 bg-white p-5">
        <p className="text-sm font-semibold text-stone-950">Evaluation Result</p>
        <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-end">
          <div>
            <div className="flex flex-wrap items-end gap-x-5 gap-y-2">
              <p className="text-5xl font-semibold tracking-normal text-stone-950">
                {formatPercent(report.passRate)}
              </p>
              <p className="pb-1 text-lg font-semibold text-stone-700">
                {report.passed} / {report.totalTests} Passed
              </p>
            </div>
            <p className="mt-3 text-sm font-semibold text-stone-700">
              {report.regressions} Regressions · {report.improvements} Improvements ·{" "}
              {failedTests.length} Quality Failures · {report.errors} Execution/Evaluator Errors
            </p>
          </div>
          <div className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm">
            {[
              ["Avg Score", formatDecimal(report.averageScore)],
              ["Avg Latency", formatLatencySeconds(report.averageLatencyMs)],
              ["Token Usage", formatTelemetry(report.totalTokens, report.telemetryCoverage.totalTokens)],
              ["Estimated Cost", formatTelemetry(report.estimatedCostUsd, report.telemetryCoverage.estimatedCostUsd, formatCurrency)],
            ].map(([label, value]) => (
              <div key={label}>
                <p className="text-xs font-semibold uppercase tracking-[0.08em] text-stone-500">
                  {label}
                </p>
                <p className="mt-1 font-semibold text-stone-950">{value}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {failedTests.length>0 && <DetailSection label="TEST RESULTS" title="Failed cases to review" description={`${failedTests.length} cases need attention. Review the expected answer, actual output, and evaluator reason.`}><ul className="space-y-3">{failedTests.slice(0,5).map(test=><li key={test.id} className="rounded-md border border-stone-200 p-3"><p className="text-sm font-semibold">{test.testName}</p><p className="mt-1 text-sm text-stone-600">{test.providerError || test.evaluatorReason}</p><p className="mt-2 text-xs text-stone-500">Expected: {test.expectedOutput.slice(0,200)}</p><p className="mt-1 text-xs text-stone-500">Actual: {test.actualOutput.slice(0,200) || "No output recorded"}</p></li>)}</ul><a href="#all-test-results" className="mt-3 inline-block text-sm underline">Review all test results</a></DetailSection>}
      <FailureRecurrences recurrences={recurrences} projectId={state.model.id} />
      {!recurrenceEvidence && <p className="text-sm text-amber-800">Recurrence history is temporarily unavailable. Current test results remain available below.</p>}
      <AnalysisSection
        evaluationId={state.evaluation.id}
        configured={aiConfigured}
        result={aiAnalysis}
        generated={shouldGenerateAi}
        autoGenerated={shouldAutoGenerateAi}
        disabled={aiDisabled}
        memoryEnabled={memoryEnabled}
        fallback={`${report.passed} of ${report.totalTests} passed; ${report.regressions} regressions and ${report.errors} execution/evaluator errors. Generate analysis for prioritized findings.`}
      />

      <DetailSection label="TEST RESULTS" title="Findings to investigate" description={aiResult ? "Evidence-linked observations and hypotheses across this run." : "Deterministic findings from stored results; AI interpretation is unavailable or not requested."}>
        {executionErrors.length > 0 && <p className="mb-3 text-sm text-amber-800">{executionErrors.length} execution/evaluator errors need repair before interpreting model quality.</p>}
        {findings.length ? <ul className="space-y-3">{findings.map((finding, index) => <li key={`${finding.title}-${index}`} className="rounded-md border border-stone-200 p-3">
          <p className="text-sm font-semibold">{"kind" in finding ? `${finding.priority} · ${finding.kind}: ` : ""}{finding.title}</p>
          <p className="mt-1 text-sm text-stone-700">{finding.description}</p>
          <div className="mt-2 flex flex-wrap gap-3">{finding.affectedTestIds.map((id) => <a key={id} href={`#${encodeURIComponent(`report-test-${id}`)}`} className="text-sm underline">{report.tests.find((test) => test.id === id)?.testName ?? id}</a>)}</div>
          <div className="mt-2 flex flex-wrap gap-2 text-xs text-stone-500">Evidence: {finding.evidenceRefs.map((ref) => <a key={ref} href={`#${encodeURIComponent(`report-evidence-${ref}`)}`} className="underline">{ref}</a>)}</div>
        </li>)}</ul> : <p className="text-sm text-stone-600">No failures, execution errors, or resolved issues were identified in the stored results.</p>}
      </DetailSection>

      <DetailSection
        label="WHAT CHANGED"
        title="What changed"
        description="Observed changes and evidence. Wording stays correlation-first unless the data proves causation."
      >
        <div className="overflow-x-auto">
          <table className="min-w-[720px] text-left text-sm">
            <thead className="border-b border-stone-200 text-xs uppercase tracking-[0.08em] text-stone-500">
              <tr>
                <th className="px-3 py-2">Change</th>
                <th className="px-3 py-2">Impact</th>
                <th className="px-3 py-2">Evidence</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-stone-200">
              {changeRows.length > 0 ? (
                changeRows.map((change) => (
                  <tr key={`${change.change}-${change.evidence}`}>
                    <td className="px-3 py-3 font-semibold text-stone-950">
                      {change.change}
                    </td>
                    <td className="px-3 py-3 text-stone-700">{change.impact}</td>
                    <td className="px-3 py-3 text-stone-600">{change.evidence}</td>
                  </tr>
                ))
              ) : relevantVersionChange ? (
                <tr>
                  <td className="px-3 py-3 font-semibold text-stone-950">
                    {relevantVersionChange.field_name ?? relevantVersionChange.change_type}
                  </td>
                  <td className="px-3 py-3 text-stone-700">
                    Observed after recorded version change
                  </td>
                  <td className="px-3 py-3 text-stone-600">
                    {relevantVersionChange.description}
                  </td>
                </tr>
              ) : (
                <tr>
                  <td className="px-3 py-3 text-stone-600" colSpan={3}>
                    No stored version change or AI-identified change is available for this run.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </DetailSection>

      <DetailSection
        label="REGRESSIONS"
        title="Regression & improvement breakdown"
        description="Rows summarize exactly what changed; full test outputs are lower in the report."
      >
        <div>
          <p className="mb-3 text-sm font-semibold text-stone-950">
            {regressionTests.length} regressions
          </p>
          <TestBreakdownTable
            tests={regressionTests}
            fallbackLabel="No regressions were detected in this run. Other failures are listed separately."
          />
        </div>
        <div className="mt-6">
          <p className="mb-3 text-sm font-semibold text-stone-950">
            {improvementTests.length} improvements
          </p>
          <TestBreakdownTable
            tests={improvementTests}
            fallbackLabel="No fail-to-pass improvements were detected in stored history."
          />
        </div>
      </DetailSection>

      {(report.failed > 0 || report.regressions > 0 || report.improvements > 0 || report.errors > 0) ? (
        <MemoryEvidenceSection
          evaluationId={state.evaluation.id}
          enabled={memoryEnabled}
          configured={hindsightConfigured}
          recallGroups={memoryRecall}
          memories={reportMemories}
          unavailableOverride={recalled.unavailable}
        />
      ) : null}

      <DetailSection
        label="NEXT ACTIONS"
        title="Recommended next actions"
        description="Each action is grounded in failed tests, version changes, stored history, or Hindsight memory."
      >
        <ol className="grid gap-4">
          {recommendations.map((recommendation, index) => (
            <li key={recommendation.id} className="border-l-2 border-stone-300 pl-4">
              <p className="text-sm font-semibold text-stone-950">
                {index + 1}. {recommendation.title}
              </p>
              <p className="mt-1 text-sm leading-6 text-stone-700">
                <span className="font-semibold">Action:</span> {recommendation.action}
              </p>
              {recommendation.evidence[0] ? (
                <p className="mt-1 text-sm leading-6 text-stone-600">
                  Evidence: {recommendation.id.startsWith("ai-") ? recommendation.evidence.map((ref) => <a key={ref} href={`#${encodeURIComponent(`report-evidence-${ref}`)}`} className="mr-2 underline">{ref}</a>) : recommendation.evidence[0]}
                </p>
              ) : null}
              <p className="mt-2 text-sm text-stone-700"><span className="font-semibold">Verify:</span> {recommendation.verification}</p>
              {recommendation.reason && <p className="mt-1 text-sm text-stone-600"><span className="font-semibold">Why:</span> {recommendation.reason}</p>}
              <div className="mt-2 flex flex-wrap gap-3">{recommendation.affectedTestIds.map((id) => <a key={id} href={`#${encodeURIComponent(`report-test-${id}`)}`} className="text-sm underline">{report.tests.find((test) => test.id === id)?.testName ?? id}</a>)}</div>
            </li>
          ))}
        </ol>
      </DetailSection>

      <DetailSection
        label="PERFORMANCE & COST"
        title="Performance & usage"
        description="Compact run telemetry from provider execution and stored evaluation rows."
      >
        <dl className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3">
          {[
            ["Average Latency", formatLatencySeconds(report.averageLatencyMs)],
            ["Duration", formatNumber(state.evaluation.duration_ms, "ms")],
            ["Run Mode", getRunMode(state.evaluation.run_metadata)],
            ["Input Tokens", formatTelemetry(inputTokens, report.telemetryCoverage.inputTokens)],
            ["Output Tokens", formatTelemetry(outputTokens, report.telemetryCoverage.outputTokens)],
            ["Total Tokens", formatTelemetry(report.totalTokens, report.telemetryCoverage.totalTokens)],
            ["Estimated Cost", formatTelemetry(report.estimatedCostUsd, report.telemetryCoverage.estimatedCostUsd, formatCurrency)],
          ].map(([label, value]) => (
            <div
              key={label}
              className="flex items-center justify-between border-b border-stone-200 py-2"
            >
              <dt className="text-stone-600">{label}</dt>
              <dd className="font-semibold text-stone-950">{value}</dd>
            </div>
          ))}
        </dl>
      </DetailSection>

      <DetailSection label="CATEGORY PERFORMANCE" title="Performance by category" description="Category metrics include all recorded results; errors are listed separately from quality failures.">
        <div className="overflow-x-auto"><table className="min-w-[700px] text-left text-sm">
          <thead className="border-b border-stone-200 text-stone-500"><tr>{["Category", "Passed / total", "Quality failures", "Errors", "Average score", "Tokens", "Cost"].map((label) => <th key={label} className="px-3 py-2">{label}</th>)}</tr></thead>
          <tbody className="divide-y divide-stone-200">{report.categoryPerformance.map((category) => <tr key={category.category}>
            <td className="px-3 py-3 font-semibold">{category.category}</td><td className="px-3 py-3">{category.passed} / {category.total}</td>
            <td className="px-3 py-3">{failedTests.filter((test) => test.category === category.category).length}</td><td className="px-3 py-3">{category.errors}</td>
            <td className="px-3 py-3">{formatDecimal(category.averageScore)}</td><td className="px-3 py-3">{formatTelemetry(category.tokens, category.telemetryCoverage.totalTokens)}</td>
            <td className="px-3 py-3">{formatTelemetry(category.estimatedCostUsd, category.telemetryCoverage.estimatedCostUsd, formatCurrency)}</td>
          </tr>)}</tbody>
        </table></div>
      </DetailSection>

      <div id="all-test-results" className="scroll-mt-6"><DetailSection
        label="ALL TEST RESULTS"
        title="Test results"
        description="Choose a filter, then open a row to inspect input, expected output, actual output, and evaluator evidence."
      >
        <ReportTestResults
          tests={report.tests}
          totalTests={report.totalTests}
          failed={report.failed}
          passed={report.passed}
          regressions={report.regressions}
        />
      </DetailSection></div>

      <DetailSection
        label="CONFIDENCE"
        title="Confidence & limitations"
        description="A compact accountability note for the analysis above."
      >
        <p className="text-sm font-semibold text-stone-950">
          Analysis Confidence:{" "}
          {aiResult?.confidence ?? (shouldGenerateAi ? "Unavailable" : "Not generated")}
        </p>
        <div className="mt-4 grid gap-5 lg:grid-cols-2">
          <div>
            <h3 className="text-sm font-semibold text-stone-950">Why</h3>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-stone-700">
              <li>{report.totalTests} current evaluation results available</li>
              <li>
                {report.tests.some((test) => test.comparisonEligibility === "COMPARABLE")
                  ? "Comparable previous version exists"
                  : "No comparable baseline was found for this run"}
              </li>
              <li>{reportMemories.length} related stored or recalled historical events</li>
            </ul>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-stone-950">Limitations</h3>
            {aiResult ? (
              <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-stone-700">
                {aiResult.limitations.map((limitation) => (
                  <li key={limitation}>{limitation}</li>
                ))}
              </ul>
            ) : (
              <p className="mt-2 text-sm leading-6 text-stone-600">
                Correlation does not prove which change caused the result movement.
              </p>
            )}
          </div>
        </div>
      </DetailSection>
      <DetailSection label="SUPPORTING EVIDENCE" title="Evidence supplied to analysis" description="Inspect cited run facts, selected test examples, version changes, and related history. Text marked as truncated has its full output in the test details.">
        <div className="space-y-2">{evidenceInventory.map((entry) => <details key={entry.id} id={`report-evidence-${entry.id}`} className="rounded-md border border-stone-200 p-3">
          <summary className="cursor-pointer text-sm font-semibold">{entry.id} · {entry.source.replaceAll("_", " ")}</summary>
          <div className="mt-2 flex flex-wrap gap-3">{entry.affectedTestIds.map((id) => <a key={id} href={`#${encodeURIComponent(`report-test-${id}`)}`} className="text-sm underline">{report.tests.find((test) => test.id === id)?.testName ?? id}</a>)}</div>
          <pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap text-xs text-stone-700">{JSON.stringify(entry.data, null, 2)}</pre>
        </details>)}</div>
      </DetailSection>
    </div>
  );
}
