import { notFound } from "next/navigation";
import Link from "next/link";
import { DetailSection } from "@/components/evaluations/detail-section";
import { FactGrid } from "@/components/evaluations/fact-grid";
import { analyzeEvaluationWithAi } from "@/lib/ai/analyze-evaluation";
import {
  completeEvaluationAnalysis,
  isEvaluationAiConfigured,
} from "@/lib/ai/client";
import type { EvaluationAnalysisStatus } from "@/lib/ai/types";
import { getEvaluationDatasetByModelId } from "@/lib/data/evaluation-engine";
import {
  getEvaluationById,
  getEvaluationResultsByEvaluationIds,
} from "@/lib/data/evaluations";
import { getEffectiveModelVersionConfiguration } from "@/lib/data/model-configurations";
import { getModelById } from "@/lib/data/models";
import {
  getVersionById,
  getVersionChangesByVersionIds,
} from "@/lib/data/versions";
import { analyzeTestResult, getStableTestKey } from "@/lib/evaluation/engine";
import { buildRunReportData, type PerTestReportRow } from "@/lib/evaluation/report-data";
import { buildEvidenceGroundedRecommendations } from "@/lib/evaluation/recommendations";
import { isHindsightConfigured } from "@/lib/hindsight/client";
import { recallEvaluationDetailMemory } from "@/lib/hindsight/recall";
import {
  backfillReportMemories,
  buildStoredReportMemories,
} from "@/lib/hindsight/report-memory";
import type { EvaluationDetailRecallGroups } from "@/lib/hindsight/recall";
import type { HindsightRecallMemory } from "@/lib/hindsight/types";

export const dynamic = "force-dynamic";

type EvaluationDetailPageProps = {
  params: Promise<{ id: string }>;
  searchParams?: Promise<{ ai?: string; memory?: string }>;
};

const dateFormatter = new Intl.DateTimeFormat("en", {
  month: "short",
  day: "numeric",
  year: "numeric",
});

function formatDate(value: string) {
  return dateFormatter.format(new Date(value));
}

function formatPercent(value: number | null) {
  return value === null ? "Not recorded" : `${Math.round(value * 100)}%`;
}

function formatNumber(value: number | null | undefined, suffix = "") {
  return typeof value === "number" && Number.isFinite(value)
    ? `${value.toLocaleString()}${suffix}`
    : "Not recorded";
}

function formatCompactNumber(value: number | null | undefined) {
  if (typeof value !== "number" || !Number.isFinite(value)) return "Not recorded";
  if (Math.abs(value) >= 1000) return `${(value / 1000).toFixed(1)}K`;
  return value.toLocaleString();
}

function formatCurrency(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value)
    ? `$${value.toFixed(6)}`
    : "Not recorded";
}

function formatDecimal(value: number | null | undefined, digits = 2) {
  return typeof value === "number" && Number.isFinite(value)
    ? value.toFixed(digits)
    : "Not recorded";
}

function formatLatencySeconds(value: number | null | undefined) {
  return typeof value === "number" && Number.isFinite(value)
    ? `${(value / 1000).toFixed(2)}s`
    : "Not recorded";
}

function formatState(value: string) {
  return value.replaceAll("_", " ");
}

function getRunMode(value: unknown) {
  return (
    typeof value === "object" &&
    value &&
    !Array.isArray(value) &&
    "mode" in value &&
    typeof value.mode === "string"
  )
    ? value.mode
    : "legacy/manual";
}

function getStatusDescription(classification: string, version: string) {
  if (classification === "REGRESSION") {
    return `A test that previously passed is failing again in ${version}.`;
  }

  if (classification === "NEW_FAILURE") {
    return `This is the first stored failure for this test in ${version}.`;
  }

  if (classification === "REPEATED_FAILURE") {
    return `This test failed before and is still failing in ${version}.`;
  }

  if (classification === "RESOLVED") {
    return "This passing result follows a previous failure.";
  }

  return "Stored results do not show a current regression for the primary test.";
}

function shouldAutoGenerateAiAnalysis(
  result: { result: string; severity: string },
  isRegression: boolean,
) {
  return (
    isRegression ||
    (result.result === "FAIL" &&
      (result.severity === "HIGH" || result.severity === "CRITICAL"))
  );
}

function PageMessage({
  title,
  description,
}: Readonly<{ title: string; description: string }>) {
  return (
    <section className="rounded-md border border-slate-200 bg-white p-6">
      <h2 className="text-sm font-semibold text-slate-950">{title}</h2>
      <p className="mt-2 text-sm leading-6 text-slate-600">{description}</p>
    </section>
  );
}

function AnalysisSection({
  evaluationId,
  configured,
  result,
  generated,
  autoGenerated,
  disabled,
  memoryEnabled,
  fallback,
}: Readonly<{
  evaluationId: string;
  configured: boolean;
  result: EvaluationAnalysisStatus | null;
  generated: boolean;
  autoGenerated: boolean;
  disabled: boolean;
  memoryEnabled: boolean;
  fallback: string;
}>) {
  const unavailableMessage = !configured
    ? "AI analysis is not configured."
    : result && !result.ok
      ? result.message
      : "AI analysis temporarily unavailable.";

  return (
    <DetailSection
      label="MODELLEDGER ANALYSIS"
      title="ModelLedger analysis"
      description="Short executive interpretation of stored facts, deterministic regression analysis, version changes, and recalled Hindsight memory."
    >
      {!generated ? (
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm leading-6 text-slate-600">
            {configured
              ? disabled
                ? "AI analysis generation is turned off for this view."
                : autoGenerated
                  ? "AI analysis is generated for high-priority issues."
                  : fallback
              : "AI analysis is not configured."}
          </p>
          {configured ? (
            <Link
              href={`/reports/${evaluationId}?memory=${memoryEnabled ? "on" : "off"}&ai=on`}
              className="inline-flex h-9 items-center justify-center rounded-md border border-slate-200 bg-white px-3 text-sm font-semibold text-slate-950 transition-colors hover:bg-slate-50 active:translate-y-px"
            >
              Generate Analysis
            </Link>
          ) : null}
        </div>
      ) : !configured || !result || !result.ok ? (
        <p className="text-sm leading-6 text-slate-600">{unavailableMessage}</p>
      ) : (
        <div className="grid gap-3">
          <p className="text-sm leading-6 text-slate-700">
            {result.analysis.executiveSummary}
          </p>
          <p className="text-sm font-semibold text-slate-950">
            Confidence: {result.analysis.confidence}
          </p>
        </div>
      )}
    </DetailSection>
  );
}

function MemoryEvidenceSection({
  evaluationId,
  enabled,
  configured,
  recallGroups,
  memories,
}: Readonly<{
  evaluationId: string;
  enabled: boolean;
  configured: boolean;
  recallGroups: EvaluationDetailRecallGroups | null;
  memories: readonly HindsightRecallMemory[];
}>) {
  const unavailable = recallGroups
    ? [
        recallGroups.similarFailures,
        recallGroups.previousResolutions,
        recallGroups.historicalRegressions,
        recallGroups.relevantVersionChanges,
      ].some((result) => !result.ok)
    : false;
  const visibleMemories = memories.slice(0, 3);

  return (
    <DetailSection
      label="HISTORICAL EVIDENCE"
      title="Historical evidence"
      description="Powered by Hindsight memory. Related stored memories are evidence, not proof of causation."
    >
      <div className="mb-4 flex flex-wrap items-center gap-2">
        <Link
          href={`/reports/${evaluationId}?memory=off`}
          className={`rounded-sm border px-3 py-1.5 text-sm font-semibold ${
            !enabled
              ? "border-slate-950 bg-slate-950 text-white"
              : "border-slate-200 text-slate-700"
          }`}
        >
          Without Memory
        </Link>
        <Link
          href={`/reports/${evaluationId}?memory=on`}
          className={`rounded-sm border px-3 py-1.5 text-sm font-semibold ${
            enabled
              ? "border-slate-950 bg-slate-950 text-white"
              : "border-slate-200 text-slate-700"
          }`}
        >
          With Memory
        </Link>
      </div>

      {!enabled ? (
        <p className="text-sm leading-6 text-slate-600">
          Without Memory mode shows only current stored facts and deterministic analysis.
        </p>
      ) : !configured || (unavailable && visibleMemories.length === 0) ? (
        <p className="text-sm leading-6 text-slate-600">
          Historical memory is temporarily unavailable.
        </p>
      ) : visibleMemories.length === 0 ? (
        <p className="text-sm leading-6 text-slate-600">
          No related historical issue found. This may be a new failure pattern.
        </p>
      ) : (
        <div className="grid gap-3">
          {visibleMemories.map((memory) => (
            <article key={memory.id} className="rounded-md border border-slate-200 p-4">
              <div className="flex flex-wrap items-center gap-2 text-xs font-medium uppercase tracking-[0.08em] text-slate-500">
                <span>{memory.eventType?.replaceAll("_", " ") ?? "Memory"}</span>
                <span>{memory.version ?? memory.modelVersionId ?? "Version not recorded"}</span>
                <span>{memory.timestamp ? formatDate(memory.timestamp) : "Date not recorded"}</span>
              </div>
              <p className="mt-2 text-sm leading-6 text-slate-700">
                {memory.content}
              </p>
            </article>
          ))}
        </div>
      )}
    </DetailSection>
  );
}

function TestBreakdownTable({
  tests,
  fallbackLabel,
}: Readonly<{ tests: readonly PerTestReportRow[]; fallbackLabel: string }>) {
  if (tests.length === 0) {
    return <p className="text-sm leading-6 text-stone-600">{fallbackLabel}</p>;
  }

  return (
    <div className="overflow-x-auto">
      <table className="min-w-[760px] text-left text-sm">
        <thead className="border-b border-stone-200 text-xs uppercase tracking-[0.08em] text-stone-500">
          <tr>
            <th className="px-3 py-2">Test</th>
            <th className="px-3 py-2">Previous</th>
            <th className="px-3 py-2">Current</th>
            <th className="px-3 py-2">Score Change</th>
            <th className="px-3 py-2">Category</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-stone-200">
          {tests.map((test) => (
            <tr key={test.id}>
              <td className="px-3 py-3 font-semibold text-stone-950">{test.testName}</td>
              <td className="px-3 py-3 text-stone-700">
                {test.baselineResult ?? "No baseline"}
              </td>
              <td className="px-3 py-3 text-stone-700">{test.result}</td>
              <td className="px-3 py-3 text-stone-700">
                {test.scoreDelta === null ? "No baseline" : formatDecimal(test.scoreDelta)}
              </td>
              <td className="px-3 py-3 text-stone-700">{test.category}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

async function getEvaluationDetailState(evaluationId: string) {
  try {
    const evaluation = await getEvaluationById(evaluationId);
    if (!evaluation) return { status: "not-found" as const };

    const [model, version, results, versionChanges, configuration] = await Promise.all([
      getModelById(evaluation.model_id),
      getVersionById(evaluation.model_version_id),
      getEvaluationResultsByEvaluationIds([evaluation.id]),
      getVersionChangesByVersionIds([evaluation.model_version_id]),
      getOptionalModelVersionConfiguration(evaluation.model_version_id),
    ]);

    if (!model || !version) return { status: "not-found" as const };

    return {
      status: "ready" as const,
      evaluation,
      model,
      version,
      results,
      versionChanges,
      configuration,
    };
  } catch (error) {
    return {
      status: "error" as const,
      description:
        error instanceof Error
          ? error.message
          : "The evaluation detail page could not load Supabase-backed data.",
    };
  }
}

async function getOptionalModelVersionConfiguration(modelVersionId: string) {
  try {
    return await getEffectiveModelVersionConfiguration(modelVersionId);
  } catch {
    return null;
  }
}

export default async function EvaluationDetailPage({
  params,
  searchParams,
}: EvaluationDetailPageProps) {
  const { id } = await params;
  const resolvedSearchParams = await searchParams;
  const memoryEnabled = resolvedSearchParams?.memory !== "off";
  const aiRequested = resolvedSearchParams?.ai === "on";
  const aiDisabled = resolvedSearchParams?.ai === "off";
  const state = await getEvaluationDetailState(id);

  if (state.status === "not-found") notFound();

  if (state.status === "error") {
    return (
      <PageMessage
        title="Evaluation unavailable"
        description={state.description}
      />
    );
  }

  const primaryResult =
    state.results.find((result) => result.result === "FAIL") ?? state.results[0];

  if (!primaryResult) {
    return (
      <PageMessage
        title="No evaluation results found"
        description="This evaluation run exists, but no individual test results are stored yet."
      />
    );
  }

  const relevantVersionChange =
    state.versionChanges.find((change) => change.change_type === "SYSTEM_PROMPT") ??
    state.versionChanges[0];
  const evaluationDataset = await getEvaluationDatasetByModelId(state.model.id);
  const report = buildRunReportData({
    evaluation: state.evaluation,
    results: state.results,
    dataset: evaluationDataset,
    configuration: state.configuration,
  });
  const analysis = analyzeTestResult(
    evaluationDataset,
    getStableTestKey(primaryResult),
    state.version.id,
  );
  const hindsightConfigured = isHindsightConfigured();
  const shouldRecallMemory =
    memoryEnabled &&
    hindsightConfigured &&
    (primaryResult.result === "FAIL" || analysis.regression.isRegression);
  const storedReportMemories = shouldRecallMemory
    ? buildStoredReportMemories({
        dataset: evaluationDataset,
        report,
        modelName: state.model.name,
      })
    : [];
  if (shouldRecallMemory) {
    await backfillReportMemories({
      modelId: state.model.id,
      modelName: state.model.name,
      dataset: evaluationDataset,
      report,
    });
  }
  const memoryRecall = shouldRecallMemory
    ? await recallEvaluationDetailMemory({
        modelId: state.model.id,
        testKey: getStableTestKey(primaryResult),
        category: primaryResult.category,
        currentFailureDescription:
          primaryResult.result === "FAIL"
            ? `${primaryResult.test_name}: expected ${primaryResult.expected_result ?? "not recorded"}; actual ${primaryResult.actual_result ?? "not recorded"}`
            : null,
        limit: 5,
      })
    : null;
  const recalledMemories = memoryRecall?.all ?? [];
  const reportMemories =
    recalledMemories.length > 0 ? recalledMemories : storedReportMemories;
  const aiConfigured = isEvaluationAiConfigured();
  const shouldAutoGenerateAi = shouldAutoGenerateAiAnalysis(
    primaryResult,
    analysis.regression.isRegression,
  );
  const shouldGenerateAi =
    aiConfigured && !aiDisabled && (shouldAutoGenerateAi || aiRequested);
  const aiAnalysis = shouldGenerateAi
    ? await analyzeEvaluationWithAi(
        {
          model: state.model,
          version: state.version,
          result: primaryResult,
          deterministicAnalysis: analysis,
          versionChanges: state.versionChanges,
          hindsightMemories: reportMemories,
        },
        completeEvaluationAnalysis,
      )
    : null;
  const recommendations = buildEvidenceGroundedRecommendations({
    report,
    memories: reportMemories,
    versionChanges: state.versionChanges,
  }).slice(0, 5);
  const aiResult = aiAnalysis && aiAnalysis.ok ? aiAnalysis.analysis : null;
  const regressionTests = report.tests.filter(
    (test) => test.classification === "REGRESSION",
  );
  const improvementTests = report.tests.filter(
    (test) => test.classification === "RESOLVED",
  );
  const failedTests = report.tests.filter((test) => test.result === "FAIL");
  const changeRows = aiResult?.keyChanges.slice(0, 4) ?? [];
  const inputTokens = report.tests.reduce((sum, test) => sum + (test.inputTokens ?? 0), 0);
  const outputTokens = report.tests.reduce((sum, test) => sum + (test.outputTokens ?? 0), 0);

  return (
    <div className="space-y-7">
      <header className="flex flex-col gap-4 border-b border-stone-200 pb-5 lg:flex-row lg:items-start lg:justify-between">
        <div>
          <p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-500">
            Run Report
          </p>
          <h1 className="mt-2 text-2xl font-semibold tracking-normal text-stone-950">
            {state.model.name}
          </h1>
          <p className="mt-2 text-sm leading-6 text-stone-600">
            Version {state.version.version} · Run {state.evaluation.id} · Evaluated{" "}
            {formatDate(state.evaluation.evaluated_at)}
          </p>
        </div>
        <nav className="flex flex-wrap gap-2">
          <Link
            href={`/compare?project=${state.model.id}`}
            className="inline-flex h-9 items-center justify-center rounded-md border border-stone-200 bg-white px-3 text-sm font-semibold text-stone-700"
          >
            Compare Version
          </Link>
          <Link
            href={`/run-evaluation?project=${state.model.id}`}
            className="inline-flex h-9 items-center justify-center rounded-md bg-stone-950 px-3 text-sm font-semibold text-white"
          >
            Run Again
          </Link>
        </nav>
      </header>

      <section className="rounded-md border border-stone-200 bg-white p-5">
        <p className="text-sm font-semibold text-stone-950">Evaluation Result</p>
        <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-end">
          <div>
            <div className="flex flex-wrap items-end gap-x-5 gap-y-2">
              <p className="text-5xl font-semibold tracking-normal text-stone-950">
                {formatPercent(report.passRate)}
              </p>
              <p className="pb-1 text-lg font-semibold text-stone-700">
                {report.passed} / {report.totalTests} Passed
              </p>
            </div>
            <p className="mt-3 text-sm font-semibold text-stone-700">
              {report.regressions} Regressions · {report.improvements} Improvements ·{" "}
              {report.failed} Failed
            </p>
          </div>
          <div className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm">
            {[
              ["Avg Score", formatDecimal(report.averageScore)],
              ["Avg Latency", formatLatencySeconds(report.averageLatencyMs)],
              ["Token Usage", formatCompactNumber(report.totalTokens)],
              ["Estimated Cost", formatCurrency(report.estimatedCostUsd)],
            ].map(([label, value]) => (
              <div key={label}>
                <p className="text-xs font-semibold uppercase tracking-[0.08em] text-stone-500">
                  {label}
                </p>
                <p className="mt-1 font-semibold text-stone-950">{value}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <AnalysisSection
        evaluationId={state.evaluation.id}
        configured={aiConfigured}
        result={aiAnalysis}
        generated={shouldGenerateAi}
        autoGenerated={shouldAutoGenerateAi}
        disabled={aiDisabled}
        memoryEnabled={memoryEnabled}
        fallback={getStatusDescription(analysis.classification, state.version.version)}
      />

      <DetailSection
        label="WHAT CHANGED"
        title="What changed"
        description="Observed changes and evidence. Wording stays correlation-first unless the data proves causation."
      >
        <div className="overflow-x-auto">
          <table className="min-w-[720px] text-left text-sm">
            <thead className="border-b border-stone-200 text-xs uppercase tracking-[0.08em] text-stone-500">
              <tr>
                <th className="px-3 py-2">Change</th>
                <th className="px-3 py-2">Impact</th>
                <th className="px-3 py-2">Evidence</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-stone-200">
              {changeRows.length > 0 ? (
                changeRows.map((change) => (
                  <tr key={`${change.change}-${change.evidence}`}>
                    <td className="px-3 py-3 font-semibold text-stone-950">
                      {change.change}
                    </td>
                    <td className="px-3 py-3 text-stone-700">{change.impact}</td>
                    <td className="px-3 py-3 text-stone-600">{change.evidence}</td>
                  </tr>
                ))
              ) : relevantVersionChange ? (
                <tr>
                  <td className="px-3 py-3 font-semibold text-stone-950">
                    {relevantVersionChange.field_name ?? relevantVersionChange.change_type}
                  </td>
                  <td className="px-3 py-3 text-stone-700">
                    Observed after recorded version change
                  </td>
                  <td className="px-3 py-3 text-stone-600">
                    {relevantVersionChange.description}
                  </td>
                </tr>
              ) : (
                <tr>
                  <td className="px-3 py-3 text-stone-600" colSpan={3}>
                    No stored version change or AI-identified change is available for this run.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </DetailSection>

      <DetailSection
        label="REGRESSIONS"
        title="Regression & improvement breakdown"
        description="Rows summarize exactly what changed; full test outputs are lower in the report."
      >
        <div>
          <p className="mb-3 text-sm font-semibold text-stone-950">
            {regressionTests.length} regressions
          </p>
          <TestBreakdownTable
            tests={regressionTests.length > 0 ? regressionTests : failedTests}
            fallbackLabel="No regressions or failures were detected in this run."
          />
        </div>
        <div className="mt-6">
          <p className="mb-3 text-sm font-semibold text-stone-950">
            {improvementTests.length} improvements
          </p>
          <TestBreakdownTable
            tests={improvementTests}
            fallbackLabel="No fail-to-pass improvements were detected in stored history."
          />
        </div>
      </DetailSection>

      {(primaryResult.result === "FAIL" || analysis.regression.isRegression) ? (
        <MemoryEvidenceSection
          evaluationId={state.evaluation.id}
          enabled={memoryEnabled}
          configured={hindsightConfigured}
          recallGroups={memoryRecall}
          memories={reportMemories}
        />
      ) : null}

      <DetailSection
        label="NEXT ACTIONS"
        title="Recommended next actions"
        description="Each action is grounded in failed tests, version changes, stored history, or Hindsight memory."
      >
        <ol className="grid gap-4">
          {recommendations.map((recommendation, index) => (
            <li key={recommendation.id} className="border-l-2 border-stone-300 pl-4">
              <p className="text-sm font-semibold text-stone-950">
                {index + 1}. {recommendation.title}
              </p>
              <p className="mt-1 text-sm leading-6 text-stone-700">
                <span className="font-semibold">Why:</span> {recommendation.action}
              </p>
              {recommendation.evidence[0] ? (
                <p className="mt-1 text-sm leading-6 text-stone-600">
                  Evidence: {recommendation.evidence[0]}
                </p>
              ) : null}
            </li>
          ))}
        </ol>
      </DetailSection>

      <DetailSection
        label="PERFORMANCE & COST"
        title="Performance & usage"
        description="Compact run telemetry from provider execution and stored evaluation rows."
      >
        <dl className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3">
          {[
            ["Average Latency", formatLatencySeconds(report.averageLatencyMs)],
            ["Duration", formatNumber(state.evaluation.duration_ms, "ms")],
            ["Run Mode", getRunMode(state.evaluation.run_metadata)],
            ["Input Tokens", formatCompactNumber(inputTokens)],
            ["Output Tokens", formatCompactNumber(outputTokens)],
            ["Total Tokens", formatCompactNumber(report.totalTokens)],
            ["Estimated Cost", formatCurrency(report.estimatedCostUsd)],
          ].map(([label, value]) => (
            <div
              key={label}
              className="flex items-center justify-between border-b border-stone-200 py-2"
            >
              <dt className="text-stone-600">{label}</dt>
              <dd className="font-semibold text-stone-950">{value}</dd>
            </div>
          ))}
        </dl>
      </DetailSection>

      <DetailSection
        label="ALL TEST RESULTS"
        title="Test results"
        description="Filters are summarized above; expand rows for input, expected output, actual output, and evaluator evidence."
      >
        <div className="mb-4 flex flex-wrap gap-2 text-sm">
          {[
            `All ${report.totalTests}`,
            `Failed ${report.failed}`,
            `Passed ${report.passed}`,
            `Regressions ${report.regressions}`,
          ].map((filter) => (
            <span
              key={filter}
              className="rounded-md border border-stone-200 px-3 py-1.5 font-semibold text-stone-700"
            >
              {filter}
            </span>
          ))}
        </div>
        <div className="grid gap-3">
          {report.tests.map((test) => (
            <details
              key={test.id}
              className="rounded-md border border-stone-200 p-3"
              open={test.result === "FAIL" || test.classification === "REGRESSION"}
            >
              <summary className="cursor-pointer text-sm font-semibold text-stone-950">
                {test.testName} · {test.result} · Score {formatDecimal(test.score)} ·{" "}
                {formatLatencySeconds(test.latencyMs)} · {formatState(test.classification)}
              </summary>
              <div className="mt-3 grid gap-3">
                <FactGrid
                  items={[
                    { label: "Category", value: test.category },
                    {
                      label: "Previous result",
                      value: test.baselineResult ?? "No baseline",
                    },
                    {
                      label: "Score change",
                      value:
                        test.scoreDelta === null
                          ? "No baseline"
                          : formatDecimal(test.scoreDelta),
                    },
                    { label: "Provider", value: test.providerStatus ?? "Not recorded" },
                    { label: "Tokens", value: formatNumber(test.totalTokens) },
                    { label: "Cost", value: formatCurrency(test.estimatedCostUsd) },
                  ]}
                />
                <div className="grid gap-3 lg:grid-cols-3">
                  <div className="rounded-md border border-stone-200 bg-stone-50 p-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.08em] text-stone-500">
                      Input
                    </p>
                    <p className="mt-2 text-sm leading-6 text-stone-700">{test.input}</p>
                  </div>
                  <div className="rounded-md border border-stone-200 bg-stone-50 p-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.08em] text-stone-500">
                      Expected Output
                    </p>
                    <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-stone-700">
                      {test.expectedOutput}
                    </p>
                  </div>
                  <div className="rounded-md border border-stone-200 bg-stone-50 p-3">
                    <p className="text-xs font-semibold uppercase tracking-[0.08em] text-stone-500">
                      Actual Output
                    </p>
                    <p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-stone-700">
                      {test.actualOutput || "No output recorded."}
                    </p>
                  </div>
                </div>
                <details className="rounded-md border border-stone-200 p-3">
                  <summary className="cursor-pointer text-sm font-semibold text-stone-950">
                    Evaluator explanation and evidence
                  </summary>
                  <p className="mt-2 text-sm leading-6 text-stone-700">
                    {test.evaluatorReason ?? "No evaluator reason recorded."}
                  </p>
                  <pre className="mt-2 max-h-72 overflow-auto rounded-md bg-stone-950 p-3 text-xs text-stone-50">
                    {test.evaluatorEvidence}
                  </pre>
                </details>
              </div>
            </details>
          ))}
        </div>
      </DetailSection>

      <DetailSection
        label="CONFIDENCE"
        title="Confidence & limitations"
        description="A compact accountability note for the analysis above."
      >
        <p className="text-sm font-semibold text-stone-950">
          Analysis Confidence:{" "}
          {aiResult?.confidence ?? (shouldGenerateAi ? "Unavailable" : "Not generated")}
        </p>
        <div className="mt-4 grid gap-5 lg:grid-cols-2">
          <div>
            <h3 className="text-sm font-semibold text-stone-950">Why</h3>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-stone-700">
              <li>{report.totalTests} current evaluation results available</li>
              <li>
                {analysis.history.length > 1
                  ? "Comparable previous version exists"
                  : "No comparable previous version was found for the primary test"}
              </li>
              <li>{reportMemories.length} relevant historical events recalled</li>
            </ul>
          </div>
          <div>
            <h3 className="text-sm font-semibold text-stone-950">Limitations</h3>
            {aiResult ? (
              <ul className="mt-2 list-disc space-y-1 pl-5 text-sm leading-6 text-stone-700">
                {aiResult.limitations.map((limitation) => (
                  <li key={limitation}>{limitation}</li>
                ))}
              </ul>
            ) : (
              <p className="mt-2 text-sm leading-6 text-stone-600">
                Correlation does not prove which change caused the result movement.
              </p>
            )}
          </div>
        </div>
      </DetailSection>
    </div>
  );
}
