import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile,readdir } from "node:fs/promises";
import { PGlite } from "@electric-sql/pglite";

test("deployment ownership, storage policies, idempotency and atomic allowances",async()=>{
 const db=new PGlite();
 try {
  await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create function auth.jwt() returns jsonb language sql stable as $$select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb$$;grant usage on schema public,auth to anon,authenticated,service_role;create schema storage;create table storage.buckets(id text primary key,name text,public boolean);create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert on storage.objects to authenticated;`);
  for(const file of (await readdir("supabase/migrations")).filter(n=>n.endsWith(".sql")).sort())await db.exec((await readFile(`supabase/migrations/${file}`,"utf8")).replace("create extension if not exists pgcrypto;",""));
  await db.exec("grant select on public.models,public.model_versions,public.evaluations to service_role");
  const query=(sql,args=[])=>db.query(sql,args);
  const login=async user=>{await db.exec("reset role");await query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:user,role:"authenticated"})]);await db.exec("set role authenticated");};
  const settings={source:"upload",reuseTests:true,files:[{path:"config.json",size:100}]};
  const create=async(key,project=null,version="V1")=>(await query("select public.create_guided_project($1,'Project','Private','"+version+"',$2::jsonb,'[]'::jsonb,$3::uuid) id",[key,JSON.stringify(settings),project])).rows[0].id;
  await login("user_a");const id=await create("key-a");assert.equal(await create("key-a"),id);
  const op=(await query("select * from model_onboarding where id=$1",[id])).rows[0];
  assert.equal((await query("select * from models")).rows.length,1);
  await assert.rejects(query("select * from model_private_credentials"));
  await assert.rejects(query("insert into deployment_allowances(owner_user_id,enabled)values('user_a',true)"));
  await assert.rejects(query("select claim_model_job($1,'user_a',gen_random_uuid())",[id]));
  await login("user_b");assert.equal((await query("select * from model_onboarding")).rows.length,0);
  await assert.rejects(create("forged-project",op.model_id,"V2"));
  await assert.rejects(query("insert into model_onboarding(owner_user_id,model_id,model_version_id,idempotency_key)values('user_b',$1,$2,'forged')",[op.model_id,op.model_version_id]));
  await db.exec("reset role");
  await query("update model_onboarding set stage='uploading' where id=$1",[id]);
  await login("user_a");
  await assert.rejects(query("insert into storage.objects(bucket_id,name,metadata)values('model-artifacts',$1,'{\"contentLength\":100}')",[`user_a/${id}/config.json`]));
  // Legacy objects remain readable only by their owner; new browser writes are retired.
  await db.exec("reset role");
  await query("insert into storage.objects(bucket_id,name,metadata)values('model-artifacts',$1,'{\"contentLength\":100}')",[`user_a/${id}/config.json`]);
  await login("user_a");
  assert.equal((await query("select * from storage.objects")).rows.length,1);
  await assert.rejects(query("insert into storage.objects(bucket_id,name,metadata)values('model-artifacts',$1,'{\"contentLength\":1000}')",[`user_a/${id}/config.json`]));
  await assert.rejects(query("insert into storage.objects(bucket_id,name)values('model-artifacts',$1)",[`user_a/${id}/unknown.bin`]));
  await login("user_b");assert.equal((await query("select * from storage.objects")).rows.length,0);
  await assert.rejects(query("insert into storage.objects(bucket_id,name)values('model-artifacts',$1)",[`user_a/${id}/config.json`]));
  await db.exec("reset role");
  await query("insert into deployment_allowances(owner_user_id,enabled,remaining_seconds,max_job_seconds)values('user_a',true,120,60)");
  await query("update model_onboarding set stage='queued' where id=$1",[id]);
  await db.exec("set role service_role");
  const lease="11111111-1111-4111-a111-111111111111";
  assert.ok((await query("select claim_model_job($1,'user_a',$2) job",[id,lease])).rows[0].job);
  assert.equal((await query("select remaining_seconds from deployment_allowances where owner_user_id='user_a'")).rows[0].remaining_seconds,60);
  assert.equal((await query("select claim_model_job($1,'user_a',gen_random_uuid()) job",[id])).rows[0].job,null);
  await query("select finish_model_job($1,$2,20)",[id,lease]);
  assert.equal((await query("select remaining_seconds from deployment_allowances where owner_user_id='user_a'")).rows[0].remaining_seconds,100);
  await query("select finish_model_job($1,$2,20)",[id,lease]);
  assert.equal((await query("select remaining_seconds from deployment_allowances where owner_user_id='user_a'")).rows[0].remaining_seconds,100);
  await query("update model_onboarding set stage='cancelled',cancel_requested=true where id=$1",[id]);
  assert.equal((await query("select claim_model_job($1,'user_a',gen_random_uuid()) job",[id])).rows[0].job,null);
  await query("update model_onboarding set stage='queued',cancel_requested=false where id=$1",[id]);
  await query("update deployment_allowances set remaining_seconds=0 where owner_user_id='user_a'");
  assert.equal((await query("select claim_model_job($1,'user_a',gen_random_uuid()) job",[id])).rows[0].job,null);
  assert.match((await query("select error from model_onboarding where id=$1",[id])).rows[0].error,/allowance/);
  await query("update model_onboarding set settings=jsonb_set(settings,'{source}','\"huggingface\"') where id=$1",[id]);
  await query("update deployment_allowances set max_storage_bytes=1000 where owner_user_id='user_a'");
  await query("select reserve_model_import($1,'user_a',800,$2)",[id,"a".repeat(40)]);
  await assert.rejects(query("select reserve_model_import($1,'user_a',1001,$2)",[id,"a".repeat(40)]));
  assert.equal(Number((await query("select artifact_bytes from model_onboarding where id=$1",[id])).rows[0].artifact_bytes),800);
  await db.exec("reset role");await login("user_b");await assert.rejects(query("select * from model_private_credentials"));
  await db.exec("reset role");
  const report=(await query("insert into evaluations(model_id,model_version_id,name,evaluated_at)values($1,$2,'Saved model report',now()) returning id",[op.model_id,op.model_version_id])).rows[0].id;
  const testCase=(await query("insert into test_cases(model_id,model_version_id,stable_key,name,category,input,expected_output)values($1,$2,'kept-test','Kept test','basic','Hello','Hello') returning id",[op.model_id,op.model_version_id])).rows[0].id;
  await query("update model_onboarding set evaluation_id=$2,stage='ready' where id=$1",[id,report]);
  await query("insert into model_private_credentials(operation_id,ciphertext)values($1,'private-test-secret')",[id]);
  await db.exec("set role service_role");
  assert.equal((await query("delete from model_onboarding where id=$1 and owner_user_id='user_b' returning id",[id])).rows.length,0);
  assert.equal((await query("delete from model_onboarding where id=$1 and owner_user_id='user_a' returning id",[id])).rows.length,1);
  assert.equal((await query("select * from model_private_credentials where operation_id=$1",[id])).rows.length,0);
  await db.exec("reset role");
  assert.equal((await query("select id from models where id=$1",[op.model_id])).rows.length,1);
  assert.equal((await query("select id from model_versions where id=$1",[op.model_version_id])).rows.length,1);
  assert.equal((await query("select id from evaluations where id=$1",[report])).rows.length,1);
  assert.equal((await query("select id from test_cases where id=$1",[testCase])).rows.length,1);
  await login("user_a");
  const replacementId=await create("replacement-model",op.model_id,"replacement-version");
  assert.notEqual(replacementId,id);
 } finally {await db.close();}
});
